spring:
  application:
    name: IDENTITY-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898
  
management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:    tracing:      endpoint: http://localhost:9411/api/v2/spans
    
