eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8761
  
management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans