server:
  port: 8082

spring:
  application:
    name: PAYMENT-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      
management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
